### ISSUE TITLE
Displying block position can be improved

### ISSUE THREAD

**Issue by yushincho** [xiph/aomanalyzer#13]
https://goo.gl/YvqDBD

In "Block Info" tab,
Instead of current "mi_col x mi_row" format, can be shown as "(mi_col, mi_row) = ($mi_col, $mi_row)"

**Comment by mbebenita** [comment]
Fixed in https://github.com/mbebenita/aomanalyzer/commit/4130dec736802570cf59ee710b68702d94341db0
