### ISSUE TITLE
Problem with latest react-select package

### ISSUE THREAD

**Issue by muman613** [xiph/aomanalyzer#37]
Hello,

I just encountered a problem which I was able to determine was caused by a revision to the react-select component.

The <LocalAnalyzer> uses the select component and what I found was that when I recently tried using the LocalAnalyzer I was shown a blank browser window after the 'Downloading AWCY Runs' dialog. I looked into the console log and saw that the problem was related to a Render call in the component.

I then looked at a repository I checked out in august of this year. There things worked. I compared the versions of the npm components and started rolling back each one. 

It seems that react-select@1.0.0-rc.10 is the culprit in this case. When I rolled it back to rc.5 then the LocalAnalyzer started to work again.

Maybe the version # could be pegged to rc.5 until the bug with rc.10 is resolved.

Thank you,
Michael Uman

**Comment by mbebenita** [comment]
I see, thanks for the bug report. I'll follow up with a patch to update the latest dependencies, and fix them so things hopefully don't break in the future.

**Comment by mbebenita** [comment]
Fixed by #38

**Comment by muman613** [comment]
Excellent work! Thank you!
