### ISSUE TITLE
motion vectors scaling

### ISSUE THREAD

**Issue by kedartatwawadi** [xiph/aomanalyzer#83]
Hello! Thanks for the nice tool :). 

Are the motion vector numbers scaled by 8? 
(for example in the picture below, the mv value plotted is 11, while the number shown is 88).

![image](https://user-images.githubusercontent.com/1708665/87365895-3e23fc00-c52c-11ea-9660-f01d505290c8.png)

**Comment by tdaede** [comment]
Yes, it's because in the AV1 bitstream, motion vectors are encoded at 1/8 resolution.
